if(GS_LIVO_USE_SANITIZER)
    if(CMAKE_BUILD_TYPE MATCHES "Debug")
        add_compile_options(-fsanitize=address,undefined -fno-omit-frame-pointer)
        add_link_options(-fsanitize=address,undefined)
        message(STATUS "Sanitizers: ASAN + UBSan enabled")
    else()
        message(WARNING "Sanitizers requested but build type is not Debug. Ignoring.")
    endif()
endif()
